### ISSUE TITLE
<使用 IDE 编译调试 Mlt framework>这篇文章在xcode环境下如何编译？

### ISSUE THREAD

**Issue by Travis990** [gandalfliang/gandalfliang.github.io#1]
我 下载你 分支：cmake的demo,
编译不过
![image](https://user-images.githubusercontent.com/6883210/58847584-140bd380-86b6-11e9-8972-d9f6d7a7bb6f.png)

**Comment by gandalfliang** [comment]
fixed: https://github.com/gandalfliang/mlt/commit/80873cf8ee583c983407e37c5c4f73086945fe69
